baseurl: /
languageCode: en-GB
title: Homepage
markup:
  goldmark:
    renderer:
      unsafe: true
params:
  nav:
    enable: true
  logo: img/k-logo.png
  theme_color: "#49a483"
  description_photo: /img/katprofilesquare.jpg
  process:
    enable: false
    subtitle: I can help you with...
    title: Skills
  twitter: "@k_j_magee"
  favicon: /img/k-logo.png
  medium: kjmagee
  case_studies:
    enable: true
    subtitle: Check out my previous projects
    title: Case studies
  hero:
    avatar: /img/katprofilesquare.jpg
    enable: true
    resume: img/kat-magee-cv.pdf
    subtitle: "Hi! I'm Kat, a copywriter, copy editor, and certified word nerd. "
    text: >-
      Originally from the UK, I studied ancient languages and linguistics at the
      University of Cambridge. After graduating, I moved to Copenhagen, Denmark,
      where I spent six years helping international companies ace their brand,
      marketing, and communications.


      I've brought my hustle to a start-up. Helped an international design firm find the story, values, and voice behind its brand. Guided new users through onboardings. Interviewed thought leaders on everything from self-driving cars to recombinant insulin. And given countless PDFs a final (final!) proofread.


      I've found that one of my biggest strengths lies in not only being quick to understand my client's business—I'm also able to understand and empathize with their audience. With this perspective, I help my clients explain complex ideas in simple, engaging, and compelling ways.


      For my next adventure? Now I'm in Seattle, WA, and excited to bring these skills to the thriving technology scene here.
  footer:
    enable: true
  email: kjmagee30@gmail.com
  description: Portfolio of Kat Magee, a copywriter with 6+ years' experience
    writing effective sales, marketing, and internal communciations content
  linkedin: https://www.linkedin.com/in/katmagee/
