baseurl: /
languageCode: en-GB
title: Homepage
params:
  case_studies:
    enable: true
    subtitle: Case studies and writing samples
    title: My work
  description: 'Portfolio of Kat Nunn, copywriter'
  description_photo: /img/katprofilesquare.jpg
  dribbble: .
  email: kjnunn30@gmail.com
  facebook: .
  favicon: /img/favicon.png
  footer:
    enable: true
  hero:
    avatar: /img/katprofilesquare.jpg
    enable: true
    resume: /img/cv-final.pdf
    subtitle: 'Hi! I''m Kat, a copywriter, editor and certified word nerd. '
    text: >-
      I believe engaging, meaningful and effective copy starts with what the
      reader needs to know – not what the writer wants to say. 


      I currently work as a copywriter with CBC, the specialist B2B brand and
      marketing agency. I help our clients across the pharma, maritime and tech
      agencies explain complicated ideas in simple, compelling ways. 


      My background is in ancient languages and linguistics, with a degree from
      Girton College, Cambridge. (After Ancient Greek, even the most technical
      engineering jargon feels easy to translate.) Since moving to Copenhagen in
      2014, I've experienced everything from small tech startup to international
      design agency.
  linkedin: 'https://www.linkedin.com/in/katnunn/'
  logo: /img/logo.png
  medium: katnunn
  nav:
    enable: true
  process:
    enable: false
    subtitle: Full Process Design
    title: My Process
  theme_color: '#49a483'
  twitter: k_j_nunn
