baseurl: /
languageCode: en-us
title: Homepage
googleAnalytics: UA-XXXXXXXX-Y
params:
  case_studies:
    enable: true
    subtitle: Selected Works
    title: Case Studies
  description: 'Portfolio of Kat Nunn, copywriter'
  description_photo: portfolio.jpg
  email: kjnunn30@gmail.com
  facebook: ''
  favicon: favicon.png
  footer:
    enable: true
  hero:
    avatar: /img/katprofilesquare.jpg
    enable: true
    resume: ResumeCollado.pdf
    subtitle: 'Hi! I''m Kat, a copywriter, editor and problem solver. '
    text: >-
      Cambridge Classicist turned professional word-nerd, currently working as a
      copywriter with one of the world's leading strategic design agencies. I
      graduated from Girton College, Cambridge in 2014, and have since had
      experience ranging from a small startup company, to large international
      agency setting.


      I firmly believe that any good piece of writing starts with understanding
      your reader, and I'm on a vendetta against incomprehensible jargon.
  linkedin: 'https://www.linkedin.com/in/katnunn/'
  logo: logo.png
  medium: 'https://medium.com/@katnunn'
  nav:
    enable: true
  process:
    enable: false
    subtitle: Full Process Design
    title: My Process
  theme_color: '#574CDD'
  twitter: 'https://twitter.com/k_j_nunn'
