baseurl: /
languageCode: en-us
title: Homepage
googleAnalytics: UA-XXXXXXXX-Y
params:
  case_studies:
    enable: true
    subtitle: ''
    title: Case Studies
  description: 'Portfolio of Kat Nunn, copywriter'
  description_photo: portfolio.jpg
  email: kjnunn30@gmail.com
  facebook: ''
  favicon: /img/logo.png
  footer:
    enable: true
  hero:
    avatar: /img/katprofilesquare.jpg
    enable: true
    resume: /img/cv-final.pdf
    subtitle: 'Hi! I''m Kat, a copywriter, editor and problem solver. '
    text: >-
      I’m a native English speaker, human-centred writer, and certified word
      nerd, who’s passionate about creating better experiences for people with
      clear, meaningful and effective copy. 


      After graduating from Girton College, Cambridge, I moved to Copenhagen to
      pursue my career in copywriting. With experience ranging from a small
      startup company, to large international agency setting, I currently work
      as a copywriter at Designit, one of the world’s leading strategic design
      firms.
  linkedin: 'https://www.linkedin.com/in/katnunn/'
  logo: /img/logo.png
  medium: katnunn
  nav:
    enable: true
  process:
    enable: false
    subtitle: Full Process Design
    title: My Process
  theme_color: '#574CDD'
  twitter: k_j_nunn
