baseurl: /
languageCode: en-GB
title: Homepage
params:
  nav:
    enable: true
  logo: /img/logo.png
  theme_color: "#49a483"
  description_photo: /img/katprofilesquare.jpg
  process:
    enable: false
    subtitle: Full Process Design
    title: My Process
  twitter: "@k_j_magee"
  favicon: /img/favicon.png
  medium: kjmagee
  case_studies:
    enable: true
    subtitle: Case studies and writing samples
    title: My work
  hero:
    avatar: /img/katprofilesquare.jpg
    enable: true
    resume: img/kat-magee-cv.pdf
    subtitle: "Hi! I'm Kat, a copywriter, content strategist, and certified word nerd. "
    text: >-
      <!--StartFragment-->


      Originally from the UK, I studied ancient languages and linguistics at the University of Cambridge. After graduating, I moved to Copenhagen, Denmark, where I spent seven years helping international companies ace their brand, marketing, and communications.


      I've brought my hustle to a start-up. Helped an international design firm find the story, values, and voice behind its brand. Guided new users through onboardings. Interviewed thought leaders on everything from self-driving cars to recombinant insulin. And given countless PDFs a final (final!) proofread.


      I've found that one of my biggest strengths lies in not only being quick to understand my client's business – I'm also able to understand and empathize with their audience. With this perspective, I help my clients explain complex ideas in simple, engaging, and compelling ways.


      For my next adventure? Now I'm in Seattle, WA, and excited to bring these skills to the thriving technology scene here. I can help you with:


      * Research and insights

      * Concept development

      * Brand voice and tone

      * Sales and marketing content

      * Web and social copy

      * Internal communications

      * UX writing
  footer:
    enable: true
  email: kjmagee30@gmail.com
  description: Portfolio of Kat Magee, a copywriter with 7+ years' experience
    writing effective sales, marketing and internal communciations content
  linkedin: https://www.linkedin.com/in/katmagee/
