backend:
  name: git-gateway

media_folder: "site/static/img" # Folder where user uploaded files should go
public_folder: "img"

collections: # A list of collections the CMS should be able to edit
  - name: "casestudies"
    label: "Case studies"
    folder: "site/content/case-studies"
    create: true
    fields:
      - {label: "Page Title", name: "title", widget: "string", default: "Kat Nunn | "}
      - {label: "Page Description", name: "description", widget: "string"}
      - {label: "Link text", name: "nav_heading", widget: "string"}
      - {label: "Thumbnail", name: "thumbnail", widget: "image"}
      - {label: "Title", name: "case_title", widget: "string"}
      - {label: "Short Title", name: "case_short_title", widget: "string"}
      - {label: "Subtitle", name: "case_subtitle", widget: "string"}
      - {label: "Description", name: "case_description", widget: "string"}
      - {label: "Featured Image", name: "case_feature_img", widget: "image"}
      - {label: "Summary", name: "case_summary", widget: "text"}
      - {label: "Team", name: "team", widget: "list", default: ["Kat Nunn"]}
      - {label: "Roles", name: "roles", widget: "list", default: ["Role1"]}
      - {label: "Methods", name: "methods", widget: "list", default: ["Method1"]}
      - {label: "Links", name: "button_links", widget: "list", fields: [{label: "URL", name: "link", widget: "string"}, {label: "Image", name: "img", widget: "image"}, {label: "Text", name: "text", widget: "string"}] }
      - {label: "Testimonial", name: "testimonial", widget: "string"}
      - {label: "Testimonial photo", name: "testimonial_photo", widget: "image"}
      - {label: "Testimonial Author", name: "testimonial_author", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Draft", name: "draft", widget: "boolean"}
      - {label: "Body", name: "body", widget: "markdown"}
  - label: "Configuration"
    name: "configuration"
    files:
      - label: "Config"
        name: "config"
        file: "site/config.toml"
        fields:
          - {label: "Base URL", name: "baseurl", widget: "string"}
          - {label: "Language code", name: "languageCode", widget: "string"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Google analytics code", name: "googleAnalytics", widget: "string"}
          - {label: "Theme colour", name: "params.theme_color", widget: "color"}
