name: github pages

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - renovate/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@16361eb4acea8698b220b76c0d4e84e1fd22c61d # tag=v2

      - name: Yarn install
        run: yarn install

      - name: Yarn build
        run: yarn build

      - name: Archive artifact
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3
        with:
          name: dist
          path: dist
  deploy:
    needs: build
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3
        with:
          name: dist
          path: dist

      - name: Deploy
        uses: peaceiris/actions-gh-pages@bd8c6b06eba6b3d25d72b7a1767993c0aeee42e7 # v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
          cname: katmagee.net
          force_orphan: true

      - name: Save to Wayback Machine
        uses: JamieMagee/wayback@4ae44d701e1524b78987b2bd6499d8b2fffbd775 # v1.3.31
        with:
          url: katmagee.net
