name: github pages

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2

      - name: Yarn install
        run: yarn install

      - name: Yarn build
        run: yarn build

      - name: Archive artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist
  deploy:
    needs: build
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
          cname: katnunn.co.uk
          force_orphan: true

      - name: Save to Wayback Machine
        uses: JamieMagee/wayback@v1.3.0
        with:
          url: katnunn.co.uk
